---
- name: reload service spamassassin
  service: name=spamassassin state=reloaded enabled=yes

- name: restart service freshclam
  service: name=freshclam state=restarted enabled=yes

- name: restart service clamd
  service: name=clamd state=restarted enabled=yes

- name: reload service clamsmtpd
  service: name=clamsmtpd state=reloaded enabled=yes
